### ISSUE TITLE
Vytvorenie Katalógu požiadaviek

### ISSUE THREAD

**Issue by Cerulikova** [TIS2024-FMFI/gastro#1]
Zozbieranie požiadaviek od jednotlivých stakeholderov a vytvorenie uceleného katalógu.

**Comment by LeaMichalikova** [comment]
[Katalóg požiadaviek.pdf](https://github.com/user-attachments/files/17377899/Katalog.poziadaviek.pdf)

Aktualizovana verzia katalogu poziadaviek

**Comment by pavelpetrovic** [comment]
otvorene otazky:
  - moznost pridavat pouzivatelov v systeme Cesty zadanim ich mailu stale zostava?
  - eviduju sa aj cesty studentov, ked sa pre nich kvoli tomu robi nulova dohoda?
  - uzavriet otazku od kedy do kedy sa pocita gastro - ak je vopred znama, 
     resp. neznama nepritomnost do konca mesiaca - vzdy sa rata az v dalsom obdobi?
  - budu sa dokumenty o gastro stiahnute sekretarkou aj archivovat? resp. bude sa dat vygenerovat aj za predch mesiac?
  - urobit zoznam vsetkych mailov, ktore system v ktorej situacii generuje, resp. ma generovat a skontrolovat, ktore z toho aplikacia aj naozaj posiela
  
drobne komentare (zohladnite podla vlastnej uvahy):
 - v perspektive 2.1 by som ocakaval trochu lepsi uvod, nadhlad, co tie systemy robia
 - ak zamestnanec nahadzuje cestu cez pritomnost, vygeneruje to nutnost jej potvrdenia od veducej
     - ostava tato funkionalita - t.j. moze cestu zadat aj cez pritomnost, alebo sa schova?
     - ak sa prida cesta cez system Cesty, ci to stale bude v systeme pritomnost generovat poziadavku (a mail?) veducej na schvalenie cesty
  - pozrite este raz issues v systeme cesty (najma je tam SPP ma spravcu a nazov, pri vybere SPP ich uzivatel uvidi a ovela lahsie sa mu vyberu)

**Comment by pavelpetrovic** [comment]
este zopar drobnych frlosov:
- 3.2.1 zda sa mi to nejednoznacne - moze filter aj vypnut/zapnut?
- mame tam niekde? treba explicitne povedat, ze sa uz nebudu dat nahodit pracovne cesty cez Pritomnost
- 3.2.7. prosim upresnit ako sa k archivovanym da dostat
- 3.3.2 "sa bude dať vrátiť "  to sa je asi iba sekretarka
- 3.3.3. myslim si, ze sekretarka hocikedy a zamestnanec iba kym cesta nie je zaevidovana
- 3.3.4. moj navrh: prvy musi zadat spravu ten, co chce napisat text, okrem toho zaskrtne ze je to "templejtova sprava" a potom vsetci, ktori idu na rovnake miesto v rovnakom case dostanu predvyplneny formular s tym, ze mozu upravit spravu specificky pre ich okolnosti - napr. svoje vydavky vysvetlit v sprave.
- z 3.3.9. nie je jasne, ci to je dalsi filter okrem uz existujuceho najnovsie-nepotvrdene-nevyuctovane alebo ci pre kazdy z existujucich filtrov sa da zapnut usporiadanie podla kriteria v poziadavke
- 3.3.13.  ake to ma dosledky a ci sa da neksor znovu aktivovat
- 3.3.16.  je urcite jasne, co znamena nespracuje?  aby sa nestalo, ze sa len pozrie, okopiruje to odtial niekam... asi sa to nestane...
- ako volitelnu poziadavku:   systém cesty bude vedieť informácie o už vyúčtovanej pracovnej ceste odoslať do novovznikajúceho systému ŠPP, aby sa výdavok zaevidoval na príslušnom ŠPP prvku

inak schvalujem KP ako uplny, konzistetny a jednoznacny.

**Comment by Cerulikova** [comment]
"Frfloši" boli zapracovaní do KP
