### ISSUE TITLE
Vytvorenie návrhu GUI pomocou moqups

### ISSUE THREAD

**Issue by LeaMichalikova** [TIS2024-FMFI/gastro#10]
Zoznámime sa s prostredím moqups a vytvoríme v ňom návrh systému.

**Comment by Cerulikova** [comment]
**GUI, ktoré musíme navrhnúť:**

- Pracovné cesty

  - [ ] 3.3.2 - tlačidlo “späť” na vyúčtovanej a spracovanej ceste
  
  - [ ] 3.3.4 - checkmark, ktorý označí správu ako šablónu
  
  - [ ] 3.3.7 - ďalšie dve polia na ŠPP
  
  - [ ] 3.3.9 - filtre v prehľade ciest - toto sme sa snažili urobiť na stretnutí
  
  - [ ] 3.3.13 - tlačidlo na deaktivovanie používateľa + celá tá karta s deaktivovanými používateľmi + tlačidlo cez, ktoré sa na kartu dá dostať
  
  - [ ] 3.3.14 - asi aj, kde sa bude ukazovať toto
  
  - [ ] 3.3.18 - tlačidlo na zobrazenie návodu, asi?

- Prítomnosť na pracovisku

  - [ ] 3.2.1 - kde sa bude zobrazovať ten filter
  
  - [ ] 3.2.3 - tu asi stačí aby sme tlačidlo “Pracovná cesta” nahradili tlačidlom “Neplatené voľno”, keďže podľa 3.1.2 sa pracovné cesty schovajú
  
  - [ ] 3.2.5 - filter na zamestnanci/doktorandi/všetci
  
  - [ ] 3.2.6 - tlačidlo na stiahnutie xls tabuľky
  
  - [ ] 3.2.7 - dropdown na výber starších tabuliek

**Comment by Cerulikova** [comment]
Zistené problémy

- 3.3.2 - čo som skúšala, tak administrátor môže cestu editovať aj keď je spracovaní, neviem presne, čo má teda tlačidlo robiť
- do systému Prítomnosť sa mi nepodarilo vytvoriť používateľa s rolu Vedúci fakulty, teda nevieme pozrieť ako to tam vyzerá a nevieme spraviť 3.2.1

**Comment by LeaMichalikova** [comment]
https://app.moqups.com/XxVnPSl0t1vcoj78CPKJWxHrjnHfACeH/view/page/ad64222d5

link na samotný moqups projekt

**Comment by LeaMichalikova** [comment]
Pripomínam, že v pondelok 11.11. o 11:30 máme stretnutie so zadávateľkou, kde jej návrh ukážeme

**Comment by Cerulikova** [comment]
Do Moqups som pridala k ŠPP prvkom políčka na zadanie sumy, ktorá sa z nich má vyplatiť. Takisto som robila zmeny v Cesty SPP prvky, kde som pridala políčka Agentúra a Akronym projektu, aby odzrkadlovala zmeny, ktoré chceme urobiť v perzistentnej vrstve. Tiež som sa tam pokúsila navrhnúť, ako by mohla byť pridaná možnosť editácie ŠPP prvkov. **Prosím, aby sa na to niekto pozrel, či to tak môže byť.**

Okrem toho som aktualizovala, komentár vyššie (https://github.com/TIS2024-FMFI/gastro/issues/10#issuecomment-2466694340), aby bol aktuálny.

**Comment by LeaMichalikova** [comment]
Odpoveď na https://github.com/TIS2024-FMFI/gastro/issues/10#issuecomment-2480759219 :
Návrh editácie je podľa mňa vporiadku, rozumne sa predišlo zduplikovaniu formulára.

**Comment by LeaMichalikova** [comment]
KP bol aktualizovaný, moqups boli posledný krát upravené.
