### ISSUE TITLE
Návrh úprav perzistentnej vrstvy

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2024-FMFI/gastro#17]

**Comment by pavelpetrovic** [comment]
![Image](https://github.com/user-attachments/assets/17915666-a8bf-4526-a3bf-7cc557cfb0e7)

**Comment by pavelpetrovic** [comment]
![Image](https://github.com/user-attachments/assets/a42f0b88-7ad0-4421-bef0-29768fa291bd)

**Comment by Cerulikova** [comment]
Pracovné cesty

- treba pridať políčka  na ďaľšie dva ŠPP prvky
- boolean, či je používateľ aktívny

**Comment by Cerulikova** [comment]
Ešte mi napadlo, že keď urobíme v cestách nejakú zmenu dátumu cesty, tak to musíme aktualizovať aj v Prítomnosti. Že, či by sme si na to nemali dať do databázy nejaký identifikátor, aby sme k ceste vedeli priradiť jej absenciu?

**Comment by Gubledon** [comment]
Čiže teraz oni nemajú žiaden identifikátor ktorým by boli prepojení ak to vidím správne? Ak nie tak by to bol asi dobrý nápad aby sa dal aktualizovať správny záznam v Prítomnosti.
