### ISSUE TITLE
Vytvorenie podrobnej špecifikácie vonkajších interfejsov

### ISSUE THREAD

**Issue by Cerulikova** [TIS2024-FMFI/gastro#18]
> ak aplikácia komunikuje s inými aplikáciami, súbormi, zariadeniami - tieto musia byť jasne a podrobne definované

Bude komunikovať so systémom pre ŠPP

**Comment by Gubledon** [comment]
Prebehlo stretnutie s druhým tímom. Požiadavku sme vyriešili udelením prístupu druhému tímu do databázy, ktorý vyrieši administrátor systému vytvorením nového užívateľa v databáze,  pomocou ktorého získajú prístup k potrebným dátam. Na zváženie pre administrátora je vytvorenie užívateľa s obmedzenými právami zamedzujúcimi non-SELECT príkazy na databáze. Zatiaľ pre testovacie účely poskytneme druhej skupine návrh perzistentnej vrstvy aby si mohli systém lokálne testovať.
