### ISSUE TITLE
Vytvoriť plán implementácie

### ISSUE THREAD

**Issue by Cerulikova** [TIS2024-FMFI/gastro#20]
> v akom poradí sa budú implementovať, testovať a navzájom spájať jednotlivé komponenty

**Comment by Cerulikova** [comment]
Odkaz na Plán Implementácie:
https://docs.google.com/document/d/1C2PRyDvCST2zVOr-ELVeOwxVfxYCY8q5dA4yIGRXYZA/edit?usp=drive_link

**Comment by Cerulikova** [comment]
Dokončila som plán implementácie. Požiadavky som sa snažila utriediť podľa vzájomnej závyslosti a potom podľa ich dôležitosti. Tu chcem podotknúť, že čo sa týka dôležitosti požiadaviek, je to iba môj názor a teda pokiaľ sa vám zdá, že niečo treba usporiadať inak, tak to kľudne prehoďte, alebo napíšte komentár. 

Takisto som sa ku každej požiadavke, pri ktorej treba upravovať DB snažila túto informáciiu spomenúť ako jej prvý podkrok, ale možno mi niečo ušlo. Takže by bolo fajn, keby, ak na to má niekto čas, to ešte skontroloval, či niekde, som nezabudla napísať, že treba upraviť DB.

Potom, ak to už všetci odsúhlasia, tak sa môže farebný text na konci, kde sú vypísane požiadavky (kapitola "Veci z katalógu") vyhodiť. Tá tam bola iba kvôli tomu, aby sme tie požiadavky mali po ruke a mohli ľahšie utriediť.

**Comment by LeaMichalikova** [comment]
Niektoré požiadavky neboli v súlade s KP, opravila som ich.
