### ISSUE TITLE
Predstavenie návrhu používateľského rozhrania Zadávateľke

### ISSUE THREAD

**Issue by Gubledon** [TIS2024-FMFI/gastro#26]
Ukážeme  Zadávateľke náš návrh používateľského rozhrania systémov prítomnosť a cesty. Cieľom je dostať spätnú väzbu na náš návrh.

**Comment by LeaMichalikova** [comment]
Co treba doladit:
- cesty main page - zmazat dropdown, staci tlacidlo
- cesta admin ukoncena - presunut policko so sumou
- cesty spracovana cesta - presunut tlacidlo spat
