### ISSUE TITLE
PNP Pridat volitelny filter na zobrazenie ziadosti za aktualny mesiac

### ISSUE THREAD

**Issue by Juraj326** [TIS2024-FMFI/gastro#29]
3.2.1. Do časti “Schvaľovanie žiadosti o neprítomnosti na pracovisku” bude pridaný voliteľný filter, ktorý umožní zobraziť len žiadosti za aktuálny mesiac

Relevantne subory:
 - **requests.php** podstranka so ziadostami, treba upravit blok zacinajuci riadkom 21
 - **template/requests.php** generuje HTML pre podstranku kde su ziadosti, konkretne nas zaujima metoda `print_requests($year, $year_minus, $year_plus, $str, $all_months)`

**Comment by Cerulikova** [comment]
Upravila som podmienku, podľa ktorej sa filtrujú zobrazené žiadosti tak, aby po zvolení filtra sa zobrazovali len žiadosti zo súčasného mesiaca.

**Comment by Cerulikova** [comment]
Ešte som prepísala popis na linku na prpínanie filtra, tak ako sme sa dohodli pri tvorbe návrhu používateľského rozhrania. Tým pádom je toto asi hotové a budem pokračovať na #30 .

**Comment by Cerulikova** [comment]
Doplnila som popis o tom, čo som urobila do návrhu.
