### ISSUE TITLE
PNP Pridat druh nepritomnosti neplatene volno

### ISSUE THREAD

**Issue by Juraj326** [TIS2024-FMFI/gastro#31]
3.2.3. Pribudne nový druh neprítomnosti “Neplatené voľno”

Relevantne subory:
- **include/config.php** konfiguracny subor, do asociativneho pola `$sk_types` a medzi konstanty bude potrebne pridat novy druh nepritomnosti
- **ajax/calendar_set.php** formular na vytvaranie nepritomnosti, momentalne si nemyslim ze je tu treba nieco menit, ale tu sa vyuziva toto asociativne pole

**Comment by Cerulikova** [comment]
Toto som prepísala do návrhu.

**Comment by Cerulikova** [comment]
Na stretnutí 5.12. sme spolu splnili túto požiadavku.

**Comment by Juraj326** [comment]
[poziadavku sme vyriesili pridanim konstanty do asociativneho pola `$sk_types` v **include/config.php**](https://github.com/TIS2017/PritomnostNaPracovisku/commit/a23bf7e36d4971376ad762a6804e55b88fb8efdc)

**Comment by Juraj326** [comment]
Riesenie poziadavky som doplnil do navrhu.
