### ISSUE TITLE
PNP Pridat moznost zobrazit zamestnancov alebo doktorandov

### ISSUE THREAD

**Issue by Juraj326** [TIS2024-FMFI/gastro#33]
3.2.5. Pribudne možnosť zobraziť len zamestnancov alebo len doktorandov

Relevantne subory:
- **class/user.php** trieda obsahujúca informácie o používateľovi, ktoré načíta z databázy, bude potrebne pridat novu konstantu pre typ doktorand
- **template/users.php** generuje HTML pre podstranku users, tu sa nachadza metoda `print_users_person`
- **users.php** podstranka, na ktorej sa vypisuje zoznam zamestnancov, mozno bude potrebne bud upravit blok `foreach($users as $u)` alebo priamo metodu `print_users_person`
- **template/user.php** generuje HTML pre hlavicku, ponuka info o userovi. Po pridani konstanty/enumerateu pre typ doktorand bude potrebne jemne upravit tento kod aby bol stale kompatibilny
- **template/index.php** generuje HTML pre hlavnu stranku, nachadza sa tu metoda `print_index_person`a sem bude potrebne pridat dropdown s vyberom doktorand/zamestnanec, pravdepodobne do divu na riadku 24-27 
- **index.php** hlavna stranka, mozno bude potrebne implementovat filter priamo tu v bloku `foreach ($users as $u)` alebo v metode `print_index_person`

**Comment by Cerulikova** [comment]
Toto som prepísala do návrhu.

**Comment by Juraj326** [comment]
Myslim si, ze na tuto poziadavku bude potrebne vytvorit column, napr. `usertype`, ktory rozlisi medzi doktorandom a zamestnancom. Kedze obydvaja maju privilegia ako STATUS::REGULAR, tak nedava podla mna zmysel vytvarat novy STATUS::PHD_STUDENT

**Comment by Juraj326** [comment]
nvm zabudol som, ze doktorandi maju pid tvaru 9xxxxxxx

**Comment by Juraj326** [comment]
[PR](https://github.com/TIS2017/PritomnostNaPracovisku/pull/69)

Poziadavku som vyriesil pridanim dropdown menu, ktory na akciu `onchange` zavola metodu `function filter_employees`. Tato JS metoda potom skryje userov v lavej sekcii stranky `side-table`, ktory nie su zvoleneho typu. Taktiez tato metoda skryje absencie zo sekcie stranky `overview-table`, ktore prisluchaju tymto userom.

[Zmeny](https://github.com/TIS2017/PritomnostNaPracovisku/pull/69/commits)

**Comment by Cerulikova** [comment]
Pozrela som PR a mergla som to.

**Comment by Juraj326** [comment]
[PR](https://github.com/TIS2017/PritomnostNaPracovisku/pull/71)

Vsimol som si bug, ze ked sa zmeni mesiac, tak absencie sa nacitaju nanovo bez toho, aby boli prefiltrovane. Bug som fixol pridanim riadku, ktory zabezpeci aby script prebehol vzdy po nacitani overview.

[Zmeny](https://github.com/TIS2017/PritomnostNaPracovisku/pull/71/commits/d27481de7ca35fd3f1e0632ca6efd5be39753ebb)

**Comment by Juraj326** [comment]
Riesenie poziadavky som doplnil do navrhu.
