### ISSUE TITLE
PC Zoradenie zamestnancov podľa priezviska

### ISSUE THREAD

**Issue by Gubledon** [TIS2024-FMFI/gastro#37]
3.3.1 Zamestnanci budú v systéme zoradení abecedne podľa priezviska

Relevantné súbory: 

- **src/app/Models/Users** - doplnenie funkcie na vrátenie zoradenia podľa priezviska napr:
public static function getSortedByLastName()
    {
        return self::orderBy('last_name', 'asc')->get();
    }
- **src/app/Http/Controlers/BusinessTripControler.php/class BusinessTripControler/ public static function index**  - vyuzit funkciu na vratenie užívateľov podľa priezviska 
- **src/routes/web.php** routes pre aplikáciu, asi tu nebude treba nič ale uvdíme, pre istotu píšem aj toto

**Comment by Cerulikova** [comment]
Prepísané do návrhu.

**Comment by Juraj326** [comment]
[PR](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/159)

Poziadavku som vyriesil podla opisu v tomto issue.

[Zmeny](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/159/commits/4ec894211d15d65cddda49f3bd650d2631833f2f)

**Comment by Cerulikova** [comment]
Myslím, že je to vporiadku. Mergla som to teda.

**Comment by LeaMichalikova** [comment]
Navrhujem ešte zobrazovať zamestnancov vo formáte "priezvisko meno" namiesto "meno priezvisko".

**Comment by Juraj326** [comment]
[PR](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/162)

Ok zmenil som to

[Zmeny](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/162/commits/5ae546b3dbeabf3fa7069b0f5d933eb9ff00401d)

**Comment by Juraj326** [comment]
Riesenie poziadavky som doplnil do navrhu.
