### ISSUE TITLE
PC Zamedzenie nahratia duplicitnej cesty

### ISSUE THREAD

**Issue by Gubledon** [TIS2024-FMFI/gastro#39]
3.3.5 Systém nedovolí nahrať jednej osobe cestu s rovnakými údajmi viac ako raz, teda nemôžu vznikať duplicitné cesty

Relevantné súbory:

- **src/app/Models/BusinessTrip.php/class BusinessTrip** - vytvoriť funkciu isDuplicate na overenie či dané parametre ako miesto, čas cesty a užívateľ neexistujú v databáze. Tieto údaje budú vložené do funkcie ako parametre
- **src/app/Http/Controllers/BusinessTripControler.php/class BusinessTripControler/public static function store** - pridať logiku na porovnanie času a miesta pracovnej cesty pre používateľa pomocou funkcie isDuplicate, aby sa zistilo či náhodou už cesta neexistuje. Vytvoriť redirect() s správou informujúcou o duplicitnej ceste.

**Comment by Cerulikova** [comment]
Prepísané do návrhu.

**Comment by Cerulikova** [comment]
[PR](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/169)

Vytvorila som funkciu BussinesTrip::isDuplicate(), ktorá skontroluje, či v databáze existuje cesta s rovnakým uživatľským id, miestom a časom začiatku a konca.

Ak takáto cesta existuje, tak systém tuto cestu neuloží do databázy a vypíše o tom správu

**Comment by Cerulikova** [comment]
Trochu som prerobila isDuplicate(). Napadlo mi, že by bolo asi dobré, keby sa cesta mohla nahrať aj v prípade, že podobná cesta existuje ale je stornovaná. Takže, ak je v systéme už podobná cesta ale je v stave CANCELLATION_REQUEST alebo CANCELLED, tak dovolím novú cestu uložiť.

**Comment by LeaMichalikova** [comment]
Ošetrenie duplicitných ciest funguje, no príde mi že vyžaduje až príliš veľkú presnosť. Napríklad, pri dvoch cestách tej istej osoby na to isté miesto v ten istý deň, no s rozdielom času príchodu / odchodu čo i len o minútu systém takto nepovažuje za duplicitnú cestu, no podľa mňa by ešte mal.

Navrhujem, aby sa cesty vyhodnotili za duplicitné, ak sa jedná o tú istý osobu a to isté miesto, a ak začinajú a končia v rovnaké dni, no nie nutne v rovnaké časy. Toto sa dá ošetriť pomocou datetime_start / end, z ktorého sa dajú vyselektovať len priamo dni.

Taktiež navrhujem, keď sa cesta neuzná a vypíše sa správa o duplicite, aby sa vyplnené údaje zachovali vo formulári. Myslím si, že  na to stačí pridať `->withInput()` do riadku `return redirect() ...` . Prosím teda o nápravu.

**Comment by Cerulikova** [comment]
Ok, pozriem to.

**Comment by Cerulikova** [comment]
Pripomienky boli implementované a čakajú na kontrolu.

**Comment by Gubledon** [comment]
Lea prosím skontroluj to a mergni ked už si to ty kontrolovala nech to máme pozatvárané.

**Comment by LeaMichalikova** [comment]
Áno idem na to. Systém som opäť otestovala a už nemám žiadne výhrady. Mergujem to.
