### ISSUE TITLE
Zoznámiť sa so sytémami Prítomnosť a Cesty

### ISSUE THREAD

**Issue by Cerulikova** [TIS2024-FMFI/gastro#4]
Musíme sa zorientovať v systémoch, s ktorými budeme pracovať.

**Comment by Juraj326** [comment]
Najskôr je potrebné dokončiť #6 a #9.

- [ ] Task 1: Úspešné spustenie systému cesty
- [ ] Task 2: Úspešné spustenie systému prítomnosť

**Comment by Cerulikova** [comment]
Kód sme si preštudovali a rozobrali. Poznámky z našich zistení sú zaznačené v implementačných issues ako aj 4. kapitole návrhu. Vstupujeme do fázy implementácie a ďalšie problémy týkajúce sa systémov budeme riešiť v issue pre danú implementačnú úlohu. Preto tento issue už ďalej používať nebudeme a zatváram ho.
