### ISSUE TITLE
PC Obmedziť odoslanie formulára bez vyplneného ŠPP

### ISSUE THREAD

**Issue by Gubledon** [TIS2024-FMFI/gastro#40]
3.3.6 Formulár nie je možné odoslať bez uvedeného ŠPP 
- Ak ŠPP nie je zvolené pri pokuse odoslať formulár,  zobrazí sa upozornenie
- Vo formulári sa zachovajú všetky už vyplnené informácie

Relevantné súbory:

- **src/app/Http/Controllers/BusinessTripControler.php/class BusinessTripControler/private static function validateFixedTripData** - zmeniť spp_symbol_id na required namiesto nullable
- **src/app/Http/Controllers/BusinessTripControler.php/class BusinessTripControler/public static function store** - pridať logiku na odoslanie upozornenia o nevyplnom špp pričom údaje by mali zostať vyplnené

**Comment by Gubledon** [comment]
Možno bude treba kontrolovať viac položiek z špp symbolu ako napríklad suma ktorá sa má z prvku preplatiť. Nie som si teraz istý, či sa tá položka vždy vypĺňa ale ak hej mala by sa kontrolovať aj ona. Osobne si myslím, že to asi netreba.

**Comment by Cerulikova** [comment]
Prepísané do návrhu.

**Comment by Gubledon** [comment]
[PR](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/176)

Nastavil som validáciu spp prvku pri vytváraní novej cesty na povinnú/required. Všetka implementácia sa týka **src/app/Http/Controllers/BusinessTripController.php**.

[Zmeny](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/176/commits)

**Comment by Cerulikova** [comment]
Mergnuté
