### ISSUE TITLE
PC Popis do ŠPP dropdownu

### ISSUE THREAD

**Issue by Gubledon** [TIS2024-FMFI/gastro#41]
3.3.8 Do ŠPP dropdownu pri vytváraní ciest pribudne zrozumiteľný popis - agentúra, akronym projektu, zodpovedný riešiteľ

Relevantné súbory:

- **src/app/database/migrations/create_spp_symbol_table** - pridať polia do Schema::create v public function up()
- **src/app/database/factories/SppSymbolfactory.php/class SppSymbolFactory/public function definition()** - pridať polia a vytvoriť defaultný stav
- **src/app/database/seeders/SppSymbolSeeder.php** - doplnit polia pre SppSymbol::insert()
- **src/app/Http/Controllers/SppControler.php/class SPPController/public function store** - pridať všetku logiku pre spracovanie dalších 2 polí
- **src/app/Models/SppSymbol.php** - pridať prvky do protected $fillable[]
- **src/app/resources/views/spp/manage.blade.php** - pridanie polí do frontendu

**Comment by Gubledon** [comment]
Môže sa stať, že úpravy budú potrebné aj v iných funkciách/súboroch. Môžeme to prejsť spolu na nasledujúcom stretnutí alebo je možné zistíme pri implementácii.

**Comment by Cerulikova** [comment]
Prepísané do návrhu.

**Comment by Juraj326** [comment]
Vyzaduje splnenie #60

**Comment by Gubledon** [comment]
Zmeny v testovacej DB a kód som adekvátne pozmenil, čaká sa na otestovanie funkčnosti dalším členom tímu pred mergnutím pull requestu.

**Comment by Gubledon** [comment]
V issue #60 pribudol komentár so sql príkazom obsahujúcim všetky zmeny pre tabulku **spp_symbols**

**Comment by Cerulikova** [comment]
Určite je toto spravené?
Nepomýlil si si to s #54. Lebo, čo som pozerala, čo sa zmenilo v cestách, tak tam ten zrozumiteľný popis nie je. Pri vytváraní cesty stále vidno len ten SPP symbol a nie agentúru, popis a zodpovedného riešiteľa.

Videla som, že bol upravený formulár na pridávanie ŠPP prvkov, čo je super, ale ešte treba aj tam pridať možnosť upravovať existujúce prvky.

**Comment by Gubledon** [comment]
Máš pravdu, pôjdem to opraviť

**Comment by Gubledon** [comment]
[PR](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/173)

Pridal som agentúru, akronym projektu, zodpovedného riešiteľa do popisu ŠPP prvkov pri editovaní pracovnej cesty. Zmeny sa týkajú súboru **src/resources/views/business-trips/edit.blade.php**.

[Zmeny](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/173/commits)

**Comment by Cerulikova** [comment]
Vyzerá to dobre, ale ešte poprosím upraviť rovnakým spôsobom aj **create.blade.php**, aby bol popis ŠPP prvkov aj tam.

**Comment by Cerulikova** [comment]
Mergnuté
