### ISSUE TITLE
PC Pridať možnosti utriedenia ciest

### ISSUE THREAD

**Issue by Cerulikova** [TIS2024-FMFI/gastro#42]
3.3.9 V  prehľade ciest pribudne možnosť usporiadať cesty podľa rôznych kritérií, toto usporiadanie bude nezávislé na už existujúce filtre najnovšie/nepotvrdené/nevyúčtované:
1. podľa identifikátora cesty od najväčšieho po najmenší
2. podľa mesta
3. podľa dátumu

Relevantné súbory:

- **pracovne-cesty-main\src\app\Http\Controllers\BusinessTripContoller.php** - funkcia index() - vykresluje zoznam pracovných ciest, podľa zvoleného filtra (najnovšie/nepotvrdené/nevyúčtované)
- **pracovne-cesty-main\src\app\Models\BusinessTrip.php** - obsahuje funkcie na filtrovanie a usporiadavanie ciest, funkcia sortedAll() vracia všetky záznamy ciest z databázy utriedené podľa daného kľúča

**Comment by Cerulikova** [comment]
Pridané do návrhu.

**Comment by LeaMichalikova** [comment]
Presnejšie popísané usporiadanie:

1. podľa identifikátora cesty od najväčšieho po najmenší - podľa "sofia_id"
2. podľa mesta - podľa "place"
3. podľa dátumu - podľa "datetime_start", čize začiatku cesty

**Comment by LeaMichalikova** [comment]
Narazila som na zaujímavosť. Existujúci filter "najnovšie" vlastne nie je filter ale len typ usporiadania. Usporiadáva cesty podľa dátumu ich vytvorenia, čiže nie rovnako ako usporiadanie podľa dátumu, ktoré sa pozerá na čas začatia cesty. Pokiaľ nieste nikto proti, presuniem teda možnosť "najnovšie" z filtrov do usporiadania a premenujem ju na "najnovšie pridané".

**Comment by LeaMichalikova** [comment]
Pokúšala som sa ponechať mechaniku na sortovanie vo funkciách v BusinessTrip modeli, keďže tam už bol sorting načrtnutý, ale potom nefungovali filtre, takže som to celé implementovala v BusinessTrip controlleri.

**Comment by LeaMichalikova** [comment]
Dropdown sa mi nepodarilo dať presne na to isté miesto, ako sme mali navrhnuté v moqups, no má k návrhu dosť blízko.

**Comment by LeaMichalikova** [comment]
Nakoniec som ešte pridala mechaniku toho, aby zvolený filter / použivateľ ostal rovnaký aj po tom čo sa zmení usporiadanie, a takiež aby zvolené usporiadanie ostalo rovnaké aj po tom, čo sa zmení filter.

Vytvorila som teda [pull request](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/177), poprosím skontrolovať a okomentovať.

**Comment by Cerulikova** [comment]
Podľa mňa je to všetko vporiadku. A dať možnosť utriediť cesty aj bežnému používateľovi je dobrý nápad.
