### ISSUE TITLE
PC - usporiadanie štátov

### ISSUE THREAD

**Issue by Cerulikova** [TIS2024-FMFI/gastro#44]
3.3.11 *V zozname štátov bude Slovensko hneď na vrchu (Slobodová)
3.3.12 *V zozname štátov budú štáty usporiadané podľa toho, ako často sa do nich cestuje a potom podľa abecedy (Slobodová)

Relevantné súbory:

- **pracovne-cesty-main\src\resources\views\business-trips\create.blade.php** - hneď na začiatku upraviť získavanie $countries, podľa počtu evidovaných ciest
- **pracovne-cesty-main\src\resources\views\business-trips\edit.blade.php** - hneď na začiatku upraviť získavanie $countries, podľa počtu evidovaných ciest

**Comment by Cerulikova** [comment]
Prepísané do návrhu.

**Comment by Juraj326** [comment]
- [ ] Vyzaduje splnenie #60

**Comment by Juraj326** [comment]
> * Vyzaduje splnenie [Spravit zmeny v testovacich DB na zaklade navrhu zmeny perzistentnej vrstvy #60](https://github.com/TIS2024-FMFI/gastro/issues/60)

Upravil som tabulku `countries` v testovacej DB aby obsahovala stlpec `trips_count` podla #17 .

**Comment by Juraj326** [comment]
Taktiez som upravil data v tabulke `countries` aby `trips_count` obsahoval spravne hodnoty podla uz existujucich dat v `business_trips`

**Comment by Juraj326** [comment]
[PR](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/160)

Do modelu `Country.php` som pridal dve metody `public static function getSortedByTripsCount() : Collection` a `public static function makeSlovakiaFirst($countries) : Collection`. Rozdelil som ich kvoli modularite. Potom som tieto metody zavolal vo `views` suboroch podla popisu vyssie.
Navyse som pridal metody `public function incrementTripsCount() : bool` a `public function decrementTripsCount() : bool`, ktore som vyuzil v `BusinessTripController.php` aby system trackoval ako casto sa cestuje do kazdej krajiny.

[Zmeny](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/160/commits)

**Comment by Juraj326** [comment]
[PR](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/163)

Dodatocne som opravil bug kedy mohlo nastat pretecenie z dovodu dekrementovania ak je `countries.trips_count` 0

[Zmeny](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/163/commits/10ab89b4c5ef0cec7e6fee3d82831fac1dcf8450)

**Comment by Juraj326** [comment]
Riesenie poziadaviek som doplnil do navrhu.

**Comment by Cerulikova** [comment]
Super, mergla som ten druhý PR.
