### ISSUE TITLE
PC Zobrazovanie dátumu vyúčtovania

### ISSUE THREAD

**Issue by Cerulikova** [TIS2024-FMFI/gastro#47]
3.3.14 Po ukončení pracovnej cesty, bude systém ukazovať dátum, do kedy musí byť spravené vyúčtovanie - 7 pracovných dní od ukončenia cesty

Relevantné súbory:

- **pracovne-cesty-main\src\resources\views\components\trip-list-item.blade.php** - toto robí vykreslenie záznamu o jednej ceste, bude sem treba spraviť, že ak je po dátume skončenia cesty, má sa vypísať dátum, do ktorého treba spraviť vyúčtovanie
- **pracovne-cesty-main\src\resources\views\dashboard.blade.php** - v cykle volá vykreslenie všetkých ciest, možno bude treba upraviť niečo aj tu, tak som to sem dala

**Comment by Cerulikova** [comment]
Prepísane do návrh.

**Comment by Juraj326** [comment]
[PR](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/161)

Poziadavku som vyriesil podla popisu vyssie.

[Zmeny](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/161/commits/26fb6182a6f725800b98a37816b066854333fbd7)

**Comment by Juraj326** [comment]
Riesenie poziadavky som doplnil do navrhu.
