### ISSUE TITLE
Vytvorenie implementacnych issues

### ISSUE THREAD

**Issue by Juraj326** [TIS2024-FMFI/gastro#48]
- [x] 3.1.1. #35 
- [x] 3.1.2. #35 
- [x] 3.2.1. #29 
- [x] 3.2.2. #30 
- [x] 3.2.3. #31 
- [x] 3.2.4. #32 
- [x] 3.2.5. #33 
- [x] 3.2.6. #34 
- [x] 3.2.7. #34 
- [x] 3.3.1. #37 
- [x] 3.3.2. Uz je vyriesene
- [x] 3.3.3. #38 
- [x] 3.3.4. #58 
- [x] 3.3.5. #39 
- [x] 3.3.6. #40 
- [x] 3.3.7. #49 
- [x] 3.3.8. #41 
- [x] 3.3.9. #42 
- [x] 3.3.10. #43 
- [x] 3.3.11. #44 
- [x] 3.3.12. #44 
- [x] 3.3.13. #50 
- [x] 3.3.14. #47 
- [x] 3.3.15. #45 
- [x] 3.3.16. #46 
- [x] 3.3.17. #57 
- [x] 3.3.18. #51 
- [x] 3.3.19. Vyriesene pristupom do DB
- [x] 3.3.20. #52
- [x] 3.3.21. #53
- [x] 3.3.22. #54 
- [x] 3.3.23. #55 
- [x] 3.3.24. #53

**Comment by Juraj326** [comment]
ja som tento tyzden dokoncil issues pre system PNP (3.1 - 3.2)

**Comment by Cerulikova** [comment]
Wow! Som si nevšimla ten zoznam. To je super, aspoň budeme hneď vidieť, čo máme.

**Comment by Juraj326** [comment]
Issues 3.3.2. a 3.3.19. vyzeraju uz byt viriesene, to som zohladnil v zozname.
Dalej som doplnil issues pre 3.3.7., 3.3.13., 3.3.18., 3.3.20., 3.3.21., 3.3.24..
Pripadne este neskor nejake doplnim.

**Comment by Juraj326** [comment]
#53 som dokoncil, #52 dorobim poobede
