### ISSUE TITLE
PC Deaktivacia uzivatelov

### ISSUE THREAD

**Issue by Juraj326** [TIS2024-FMFI/gastro#50]
3.3.13. *Administrátor bude môcť deaktivovať používateľa zo systému podobne, ako v systéme Prítomnosť na pracovisku 
a. deaktivovaný používateľ sa nebude vedieť do systému prihlásiť
b. deaktivovaní používatelia budú zobrazení v zozname deaktivovaných používateľov systému v abecednom poradí s možnosťou opäť ich aktivovať

Relevantne subory:
* **resources/views/dashboard.blade.php** v sekcii `<x-content-box title="Prehľad">` sa vypisuje zoznam uzivatelov, sem asi sa pridaju tie checkboxy
* **resources/views/dashboard.blade.php** do divu `<div class="mb-3 btn-toolbar" role="toolbar">` pridat `<div class="mr-2 btn-group">` pre deaktivovanych uzivatelov
* **resources/views/users** sem pridat novy subor `.blade.php`, ktory bude obsahovat HTML pre stranku deaktivovanych userov
* **routes/web.php** do `Route::controller(UserController::class)` pridat routovanie na novu stranku deaktivovanych userov
* **app/Http/Controllers/UserController.php** `public function authenticate(Request $request)` do tejto metody je asi vhodne pridat logiku, ktora znemozni userovi sa prihlasit, ak je deaktivovany

**Comment by Cerulikova** [comment]
Zistila som, že existuje enumerátor UserStatus, ktorý určuje, či je používateľ aktívny (1), alebo neaktívny (0). Táto informácia je uložená aj v DB v stĺpci **status**.

**Comment by Cerulikova** [comment]
Myslím, že používanie checboxov na deaktiváciu a aktiváciu používateľa je zbytočne zložité a keďže akcia sa má aj tak vykonať po kliknutí na checkbox, rozhodla som sa použiť tlačidlo. Aj pre používateľa bude príjemnejšie klikať na tlačidlo ako do malého checkboxu.

**Comment by LeaMichalikova** [comment]
Nápad s tlačidlom namiesto checkboxov je skvelý. Rozmýšľam ešte, či by sa nehodilo niekam nejako napísať že na aký typ použivateľov (aktívni / neaktívni) sa práve pozeráme, lebo zatiaľ jediné indikátory ako to zistiť sú tie tlačidlá, čo mi nepríde veľmi priamočiaré. možno by sa hodilo vedľa "prehľad" alebo "pracovné cesty" doplniť že ide o takých a takých použivateľov, alebo niečo podobné. Alebo máte niekto lepší nápad?

**Comment by Cerulikova** [comment]
Doplnila som informáciu o tom, ktorí používatelia sú zobrazení, vedľa slova "Prehľad"

**Comment by LeaMichalikova** [comment]
Skontrolovala som to, ďalšie výhrady už nemám. Funguje to veľmi pekne a pohodlne sa s tým robí. Mergujem PR.
