### ISSUE TITLE
PC Identifikator cesty

### ISSUE THREAD

**Issue by Juraj326** [TIS2024-FMFI/gastro#53]
- [x] Zabranenie duplicit
- [x] Umoznit editaciu
* 3.3.21. Systém nedovolí administrátorovi zadať ceste identifikátor, ktorý už
má pridelený iná cesta
* 3.3.24. *Administrátor môže kedykoľvek editovať identifikátor cesty

Relevantne subory:
* **app/Http/Controllers/BusinessTripController.php** v metode `public static function confirm(Request $request, BusinessTrip $trip)` sa zadava identifikator cesty `'sofia_id' => $validatedData['sofia_id']`, tento identifikator je potrebne skontrolovat na duplicity
    * rovnako je potrebne pridat tento blok do zvysnych stavov, aby bolo umoznene editovat identifikator cesty kedykolvek
* **resources/views/business-trips/edit.blade.php** do bloku `<x-layout>` na riadku 53 pridat blok s formulárom na zmenu identifikátora cesty, pravdepodobne aj pridat nejaky kod, premennu do php bloku na zaciatku

**Comment by LeaMichalikova** [comment]
Navrhujem aj v databáze nastaviť identifikátor (sofia_id) ako UNIQUE, dodatočne sa tak predíde duplicitám.

**Comment by LeaMichalikova** [comment]
Problém s unikátnosťou identifikátora sa skomplikoval, lebo všetky cesty, ktoré ešte nemajú priradený identifikátor, majú ako identifikátor čislo 0000, a takýchto ciest môže byť naraz aj viac.

**Comment by LeaMichalikova** [comment]
Unikátnosť sa teda v kóde kontroluje, ale pripúšťa viacero ciest s identifikátorom '0000'.  Kontrola duplicít je tak hotová.

**Comment by LeaMichalikova** [comment]
Editácia je umožnená a vo formulári funguje správne, ale na hlavnej stránke s cestami sa stále zobrazuje staré id a nevedela som prísť na to prečo.

**Comment by Cerulikova** [comment]
Skontrolovala som to a žiadne chyby som už nenašla. PR je mergnutý.
