### ISSUE TITLE
PC Zmena formulára na úpravu ŠPP

### ISSUE THREAD

**Issue by Gubledon** [TIS2024-FMFI/gastro#54]
3.3.22 Formulár na úpravu ŠPP prvkov bude pozmenený: (Slobodová)
- pribudne dropdown na výber už existujúceho prvku, alebo možnosti “nový prvok”
- pri výbere možnosti “nový prvok” bude formulár prázdny a pripravený na vyplnenie údajmi
- pri výbere jedného z už existujúcich prvkov sa vo formulári zobrazia jeho podrobnosti, ktoré je možne editovať
- políčko “fond” sa odstráni
- pribudnú políčka “agentúra” a “akronym projektu”

Relevantné súbory:

- **src/app/Http/Controllers/SppControler.php/class SPPController** - pridať logiku pre výber existujúceho prvku
- **src/app/Models/SppSymbol.php** - pozrieť či netreba pridať výber existujúceho prvku
- **src/app/resources/views/spp/manage.blade.php** - pridanie dropdownu a políčok do frontendu už je aj v 3.3.8, odstránenie políčka fond

**Comment by Juraj326** [comment]
- [ ] Vyzaduje splnenie #60

**Comment by Gubledon** [comment]
[PR](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/166)

V **src/app/Http/Controllers/SPPController.php** pribudla funkcia update pre updatovanie špp prvku.
V súboroch **src/database/factories/SppSymbolFactory.php**, **src/app/Models/SppSymbol.php**, **src/database/migrations/2023_12_14_230033_create_spp_symbols_table.php**, **src/database/migrations/2023_12_14_230033_create_spp_symbols_table.php**, **src/database/seeders/SppSymbolSeeder.php** prebehlo upravenie pre políčka podľa zadania.
Do súboru **src/resources/views/spp/manage.blade.php** som pridal dropdown a logiku pre všetky políčka formulára na úpravu existujúcich špp prvkov + logiku na zobrazovanie konkrétneho textu pri určitých políčkach na základe bud pridávania nového špp prvku alebo úpravy existujúceho.
Do **src/routes/web.php** pribudli routes pre edit a update funkcie z SPPController class

[Zmeny](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/166/commits)

**Comment by Cerulikova** [comment]
Super, je to v poriadku. Mergla som PR.
