### ISSUE TITLE
PC Zlúčenie stavov doplnená a potvrdená 

### ISSUE THREAD

**Issue by Gubledon** [TIS2024-FMFI/gastro#55]
3.3.23. Stavy potvrdená a doplnená cesta sa zlúčia do stavu potvrdená

Relevantné súbory:

- **src/app/Enums/TripState.php** - stav doplnená sa zlúčia do stavu potvrdená, resp. sa vymaže tento typ "enumu"
- **src/app/Http/Controllers/BusinessTripController.php/class BusinessTripController/public function update** - zlúčiť a vymazať UPDATED do CONFIRMED

**Comment by Gubledon** [comment]
# `business_trips.state`


```mysql


UPDATE `cesty_new`.`business_trips`
SET `state` = CASE 
                 WHEN `state` <= 2 THEN `state` - 1 
                 ELSE `state` 
              END;


```

**Comment by Gubledon** [comment]
[PR](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/168)

V **src/app/Enums/TripState.php** som vymazal typ UPDATED a ostatným typom s vyšším číslom znížil hodnotu -1.  Vo všetkých ostatných funkciách v tomto súbore boli taktiež odstráne typy UPDATED.
V **src/app/Http/Controllers/BusinessTripController.php/class BusinessTripController/public function update** došlo k zlúčeniu funkcionality týchto dvoch stavov. **src/resources/views/business-trips/edit.blade.php** Nahradenie všetchých UPDATED stavom CONFIRMED. 
Dáta v databáze boli pozmenené sql príkazom z komentu vyššie. 

[Zmeny](https://github.com/TIS2023-FMFI/pracovne-cesty/pull/168/commits)

**Comment by Gubledon** [comment]
Zmeny v DB zapisujem aj do Issue #60 pre lepší prehlad.

**Comment by Cerulikova** [comment]
Opravila som drobnú chybu v popise a mergla som to.
