### ISSUE TITLE
PC Farebné rozlíšenie ikon

### ISSUE THREAD

**Issue by LeaMichalikova** [TIS2024-FMFI/gastro#61]
(dodatočná požiadavka mimo KP)
Ikony stavov ciest budú farebne rozlíšené pre lepšiu orientáciu.

Relevantné súbory:
- TripState.php - treba pridať funkciu ktorá podľa stavu vráti správnu farbu, na spôsob funkcie icon()
- state-icon.blade.php - pomocou `style` a novej funkcie vieme zmeniť farbu ikony

**Comment by LeaMichalikova** [comment]
Prislúchajúci (pull request)[https://github.com/TIS2023-FMFI/pracovne-cesty/pull/178].

**Comment by Cerulikova** [comment]
Pekne, mergujem
